# Generated by Django 4.2.5 on 2023-09-20 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('assignment_instructions', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Vocab_Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('definition', models.CharField(max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_words_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=155)),
                ('favorite_book', models.CharField(max_length=60)),
                ('representing_image', models.CharField(max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perceived_iq', models.FloatField()),
                ('overall_potential', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inspiration_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel', models.CharField(max_length=70)),
                ('author', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=5000)),
                ('explanation', models.CharField(max_length=5000)),
                ('relevance_scale', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_inspirational_books', to='parallel_place_api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion_Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_prompt', models.CharField(max_length=1170)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_by_teacher', to='parallel_place_api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=10000)),
                ('discussion_topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='discussion_comments', to='parallel_place_api.discussion_topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='characters', to='parallel_place_api.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.CharField(max_length=10000)),
                ('teacher_feedback', models.CharField(max_length=10000)),
                ('date_reviewed', models.DateField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submissions_per_assignment', to='parallel_place_api.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignments_completed_by_student', to='parallel_place_api.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_graded_by_teacher', to='parallel_place_api.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_by_teacher', to='parallel_place_api.teacher'),
        ),
        migrations.CreateModel(
            name='About_The_Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(max_length=7000000)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parallel_place_api.teacher')),
            ],
        ),
    ]
